package client

const (
	parameterAccount                string = "account"
	parameterAccountType            string = "accountType"
	parameterActionTemplate         string = "actionTemplate"
	parameterArtifact               string = "artifact"
	parameterAPIKey                 string = "apiKey"
	parameterAPIKeyID               string = "apiKeyID"
	parameterCertificate            string = "certificate"
	parameterCertificateID          string = "certificateID"
	parameterChannel                string = "channel"
	parameterEnvironment            string = "environment"
	parameterFeed                   string = "feed"
	parameterID                     string = "id"
	parameterIDs                    string = "ids"
	parameterLibraryVariableSet     string = "libraryVariableSet"
	parameterMachinePolicy          string = "machinePolicy"
	parameterName                   string = "name"
	parameterOctopusURL             string = "octopusURL"
	parameterPartialName            string = "partialName"
	parameterPath                   string = "path"
	parameterProjectID              string = "projectID"
	parameterProject                string = "project"
	parameterReplacementCertificate string = "replacementCertificate"
	parameterResource               string = "resource"
	parameterRunbook                string = "runbook"
	parameterSling                  string = "sling"
	parameterUserID                 string = "userID"
	parameterWorker                 string = "worker"
	parameterWorkerPool             string = "workerPool"
)
