package client

const (
	linkAccounts                    = "Accounts"
	linkActionTemplates             = "ActionTemplates"
	linkActionTemplatesCategories   = "ActionTemplatesCategories"
	linkActionTemplatesSearch       = "ActionTemplatesSearch"
	linkActionTemplateVersionedLogo = "ActionTemplateVersionedLogo"
	linkAuthentication              = "Authentication"
	linkCertificates                = "Certificates"
	linkChannels                    = "Channels"
	linkConfiguration               = "Configuration"
	linkDeploymentProcesses         = "DeploymentProcesses"
	linkDeployments                 = "Deployments"
	linkEnvironments                = "Environments"
	linkFeeds                       = "Feeds"
	linkInterruptions               = "Interruptions"
	linkLibraryVariableSets         = "LibraryVariables"
	linkLifecycles                  = "Lifecycles"
	linkMachines                    = "Machines"
	linkMachinePolicies             = "MachinePolicies"
	linkProjects                    = "Projects"
	linkProjectGroups               = "ProjectGroups"
	linkProjectTriggers             = "ProjectTriggers"
	linkResponsible                 = "Responsible"
	linkSelf                        = "Self"
	linkSpaces                      = "Spaces"
	linkSubmit                      = "Submit"
	linkTagSets                     = "TagSets"
	linkTenants                     = "Tenants"
	linkUsages                      = "Usages"
	linkUsers                       = "Users"
	linkVariables                   = "Variables"
)
