// Code generated by "enumer -type=RateLimitingPolicyScopeType -json -output rate_limiting_policy_scope_type_string.go"; DO NOT EDIT.

package ratelimitingpolicies

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RateLimitingPolicyScopeTypeName = "UnauthenticatedAuthenticatedHumanAuthenticatedAgent"

var _RateLimitingPolicyScopeTypeIndex = [...]uint8{0, 15, 33, 51}

const _RateLimitingPolicyScopeTypeLowerName = "unauthenticatedauthenticatedhumanauthenticatedagent"

func (i RateLimitingPolicyScopeType) String() string {
	if i < 0 || i >= RateLimitingPolicyScopeType(len(_RateLimitingPolicyScopeTypeIndex)-1) {
		return fmt.Sprintf("RateLimitingPolicyScopeType(%d)", i)
	}
	return _RateLimitingPolicyScopeTypeName[_RateLimitingPolicyScopeTypeIndex[i]:_RateLimitingPolicyScopeTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RateLimitingPolicyScopeTypeNoOp() {
	var x [1]struct{}
	_ = x[Unauthenticated-(0)]
	_ = x[AuthenticatedHuman-(1)]
	_ = x[AuthenticatedAgent-(2)]
}

var _RateLimitingPolicyScopeTypeValues = []RateLimitingPolicyScopeType{Unauthenticated, AuthenticatedHuman, AuthenticatedAgent}

var _RateLimitingPolicyScopeTypeNameToValueMap = map[string]RateLimitingPolicyScopeType{
	_RateLimitingPolicyScopeTypeName[0:15]:       Unauthenticated,
	_RateLimitingPolicyScopeTypeLowerName[0:15]:  Unauthenticated,
	_RateLimitingPolicyScopeTypeName[15:33]:      AuthenticatedHuman,
	_RateLimitingPolicyScopeTypeLowerName[15:33]: AuthenticatedHuman,
	_RateLimitingPolicyScopeTypeName[33:51]:      AuthenticatedAgent,
	_RateLimitingPolicyScopeTypeLowerName[33:51]: AuthenticatedAgent,
}

var _RateLimitingPolicyScopeTypeNames = []string{
	_RateLimitingPolicyScopeTypeName[0:15],
	_RateLimitingPolicyScopeTypeName[15:33],
	_RateLimitingPolicyScopeTypeName[33:51],
}

// RateLimitingPolicyScopeTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RateLimitingPolicyScopeTypeString(s string) (RateLimitingPolicyScopeType, error) {
	if val, ok := _RateLimitingPolicyScopeTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RateLimitingPolicyScopeTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RateLimitingPolicyScopeType values", s)
}

// RateLimitingPolicyScopeTypeValues returns all values of the enum
func RateLimitingPolicyScopeTypeValues() []RateLimitingPolicyScopeType {
	return _RateLimitingPolicyScopeTypeValues
}

// RateLimitingPolicyScopeTypeStrings returns a slice of all String values of the enum
func RateLimitingPolicyScopeTypeStrings() []string {
	strs := make([]string, len(_RateLimitingPolicyScopeTypeNames))
	copy(strs, _RateLimitingPolicyScopeTypeNames)
	return strs
}

// IsARateLimitingPolicyScopeType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RateLimitingPolicyScopeType) IsARateLimitingPolicyScopeType() bool {
	for _, v := range _RateLimitingPolicyScopeTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RateLimitingPolicyScopeType
func (i RateLimitingPolicyScopeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RateLimitingPolicyScopeType
func (i *RateLimitingPolicyScopeType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RateLimitingPolicyScopeType should be a string, got %s", data)
	}

	var err error
	*i, err = RateLimitingPolicyScopeTypeString(s)
	return err
}
