package octopusdeploy

const (
	OperationAdd                     string = "Add"
	OperationAPIAdd                  string = "apiAdd"
	OperationAPIDelete               string = "apiDelete"
	OperationAPIGet                  string = "apiGet"
	OperationAPIPost                 string = "apiPost"
	OperationAPIUpdate               string = "apiUpdate"
	OperationDelete                  string = "Delete"
	OperationDeleteByID              string = "DeleteByID"
	OperationGet                     string = "Get"
	OperationGetAPIKeyByID           string = "GetAPIKeyByID"
	OperationGetAPIKeys              string = "GetAPIKeys"
	OperationGetAuthentication       string = "GetAuthentication"
	OperationGetAuthenticationByUser string = "GetAuthenticationByUser"
	OperationGetByID                 string = "GetByID"
	OperationGetByIDs                string = "GetByIDs"
	OperationGetByName               string = "GetByName"
	OperationGetByPartialName        string = "GetByPartialName"
	OperationGetByProjectID          string = "GetByProjectID"
	OperationGetByUserID             string = "GetByUserID"
	OperationGetChannels             string = "GetChannels"
	OperationGetDeployments          string = "GetDeployments"
	OperationGetProject              string = "GetProject"
	OperationGetReleases             string = "GetReleases"
	OperationGetSummary              string = "GetSummary"
	OperationInstall                 string = "Install"
	OperationReplace                 string = "Replace"
	OperationUpdate                  string = "Update"
)
