package resources

type SpacePermissions struct {
	AccountCreate                     []UserPermissionRestriction `json:"AccountCreate"`
	AccountDelete                     []UserPermissionRestriction `json:"AccountDelete"`
	AccountEdit                       []UserPermissionRestriction `json:"AccountEdit"`
	AccountView                       []UserPermissionRestriction `json:"AccountView"`
	ActionTemplateCreate              []UserPermissionRestriction `json:"ActionTemplateCreate"`
	ActionTemplateDelete              []UserPermissionRestriction `json:"ActionTemplateDelete"`
	ActionTemplateEdit                []UserPermissionRestriction `json:"ActionTemplateEdit"`
	ActionTemplateView                []UserPermissionRestriction `json:"ActionTemplateView"`
	AdministerSystem                  []UserPermissionRestriction `json:"AdministerSystem"`
	ArtifactCreate                    []UserPermissionRestriction `json:"ArtifactCreate"`
	ArtifactDelete                    []UserPermissionRestriction `json:"ArtifactDelete"`
	ArtifactEdit                      []UserPermissionRestriction `json:"ArtifactEdit"`
	ArtifactView                      []UserPermissionRestriction `json:"ArtifactView"`
	BuildInformationAdminister        []UserPermissionRestriction `json:"BuildInformationAdminister"`
	BuildInformationPush              []UserPermissionRestriction `json:"BuildInformationPush"`
	BuiltInFeedAdminister             []UserPermissionRestriction `json:"BuiltInFeedAdminister"`
	BuiltInFeedDownload               []UserPermissionRestriction `json:"BuiltInFeedDownload"`
	BuiltInFeedPush                   []UserPermissionRestriction `json:"BuiltInFeedPush"`
	CertificateCreate                 []UserPermissionRestriction `json:"CertificateCreate"`
	CertificateDelete                 []UserPermissionRestriction `json:"CertificateDelete"`
	CertificateEdit                   []UserPermissionRestriction `json:"CertificateEdit"`
	CertificateExportPrivateKey       []UserPermissionRestriction `json:"CertificateExportPrivateKey"`
	CertificateView                   []UserPermissionRestriction `json:"CertificateView"`
	ConfigureServer                   []UserPermissionRestriction `json:"ConfigureServer"`
	DefectReport                      []UserPermissionRestriction `json:"DefectReport"`
	DefectResolve                     []UserPermissionRestriction `json:"DefectResolve"`
	DeploymentCreate                  []UserPermissionRestriction `json:"DeploymentCreate"`
	DeploymentDelete                  []UserPermissionRestriction `json:"DeploymentDelete"`
	DeploymentView                    []UserPermissionRestriction `json:"DeploymentView"`
	EnvironmentCreate                 []UserPermissionRestriction `json:"EnvironmentCreate"`
	EnvironmentDelete                 []UserPermissionRestriction `json:"EnvironmentDelete"`
	EnvironmentEdit                   []UserPermissionRestriction `json:"EnvironmentEdit"`
	EnvironmentView                   []UserPermissionRestriction `json:"EnvironmentView"`
	EventView                         []UserPermissionRestriction `json:"EventView"`
	FeedEdit                          []UserPermissionRestriction `json:"FeedEdit"`
	FeedView                          []UserPermissionRestriction `json:"FeedView"`
	InterruptionSubmit                []UserPermissionRestriction `json:"InterruptionSubmit"`
	InterruptionView                  []UserPermissionRestriction `json:"InterruptionView"`
	InterruptionViewSubmitResponsible []UserPermissionRestriction `json:"InterruptionViewSubmitResponsible"`
	LibraryVariableSetCreate          []UserPermissionRestriction `json:"LibraryVariableSetCreate"`
	LibraryVariableSetDelete          []UserPermissionRestriction `json:"LibraryVariableSetDelete"`
	LibraryVariableSetEdit            []UserPermissionRestriction `json:"LibraryVariableSetEdit"`
	LibraryVariableSetView            []UserPermissionRestriction `json:"LibraryVariableSetView"`
	LifecycleCreate                   []UserPermissionRestriction `json:"LifecycleCreate"`
	LifecycleDelete                   []UserPermissionRestriction `json:"LifecycleDelete"`
	LifecycleEdit                     []UserPermissionRestriction `json:"LifecycleEdit"`
	LifecycleView                     []UserPermissionRestriction `json:"LifecycleView"`
	MachineCreate                     []UserPermissionRestriction `json:"MachineCreate"`
	MachineDelete                     []UserPermissionRestriction `json:"MachineDelete"`
	MachineEdit                       []UserPermissionRestriction `json:"MachineEdit"`
	MachinePolicyCreate               []UserPermissionRestriction `json:"MachinePolicyCreate"`
	MachinePolicyDelete               []UserPermissionRestriction `json:"MachinePolicyDelete"`
	MachinePolicyEdit                 []UserPermissionRestriction `json:"MachinePolicyEdit"`
	MachinePolicyView                 []UserPermissionRestriction `json:"MachinePolicyView"`
	MachineView                       []UserPermissionRestriction `json:"MachineView"`
	ProcessEdit                       []UserPermissionRestriction `json:"ProcessEdit"`
	ProcessView                       []UserPermissionRestriction `json:"ProcessView"`
	ProjectCreate                     []UserPermissionRestriction `json:"ProjectCreate"`
	ProjectDelete                     []UserPermissionRestriction `json:"ProjectDelete"`
	ProjectEdit                       []UserPermissionRestriction `json:"ProjectEdit"`
	ProjectGroupCreate                []UserPermissionRestriction `json:"ProjectGroupCreate"`
	ProjectGroupDelete                []UserPermissionRestriction `json:"ProjectGroupDelete"`
	ProjectGroupEdit                  []UserPermissionRestriction `json:"ProjectGroupEdit"`
	ProjectGroupView                  []UserPermissionRestriction `json:"ProjectGroupView"`
	ProjectView                       []UserPermissionRestriction `json:"ProjectView"`
	ProxyCreate                       []UserPermissionRestriction `json:"ProxyCreate"`
	ProxyDelete                       []UserPermissionRestriction `json:"ProxyDelete"`
	ProxyEdit                         []UserPermissionRestriction `json:"ProxyEdit"`
	ProxyView                         []UserPermissionRestriction `json:"ProxyView"`
	ReleaseCreate                     []UserPermissionRestriction `json:"ReleaseCreate"`
	ReleaseDelete                     []UserPermissionRestriction `json:"ReleaseDelete"`
	ReleaseEdit                       []UserPermissionRestriction `json:"ReleaseEdit"`
	ReleaseView                       []UserPermissionRestriction `json:"ReleaseView"`
	RunbookEdit                       []UserPermissionRestriction `json:"RunbookEdit"`
	RunbookRunCreate                  []UserPermissionRestriction `json:"RunbookRunCreate"`
	RunbookRunDelete                  []UserPermissionRestriction `json:"RunbookRunDelete"`
	RunbookRunView                    []UserPermissionRestriction `json:"RunbookRunView"`
	RunbookView                       []UserPermissionRestriction `json:"RunbookView"`
	SpaceCreate                       []UserPermissionRestriction `json:"SpaceCreate"`
	SpaceDelete                       []UserPermissionRestriction `json:"SpaceDelete"`
	SpaceEdit                         []UserPermissionRestriction `json:"SpaceEdit"`
	SpaceView                         []UserPermissionRestriction `json:"SpaceView"`
	SubscriptionCreate                []UserPermissionRestriction `json:"SubscriptionCreate"`
	SubscriptionDelete                []UserPermissionRestriction `json:"SubscriptionDelete"`
	SubscriptionEdit                  []UserPermissionRestriction `json:"SubscriptionEdit"`
	SubscriptionView                  []UserPermissionRestriction `json:"SubscriptionView"`
	TagSetCreate                      []UserPermissionRestriction `json:"TagSetCreate"`
	TagSetDelete                      []UserPermissionRestriction `json:"TagSetDelete"`
	TagSetEdit                        []UserPermissionRestriction `json:"TagSetEdit"`
	TaskCancel                        []UserPermissionRestriction `json:"TaskCancel"`
	TaskCreate                        []UserPermissionRestriction `json:"TaskCreate"`
	TaskEdit                          []UserPermissionRestriction `json:"TaskEdit"`
	TaskView                          []UserPermissionRestriction `json:"TaskView"`
	TeamCreate                        []UserPermissionRestriction `json:"TeamCreate"`
	TeamDelete                        []UserPermissionRestriction `json:"TeamDelete"`
	TeamEdit                          []UserPermissionRestriction `json:"TeamEdit"`
	TeamView                          []UserPermissionRestriction `json:"TeamView"`
	TenantCreate                      []UserPermissionRestriction `json:"TenantCreate"`
	TenantDelete                      []UserPermissionRestriction `json:"TenantDelete"`
	TenantEdit                        []UserPermissionRestriction `json:"TenantEdit"`
	TenantView                        []UserPermissionRestriction `json:"TenantView"`
	TriggerCreate                     []UserPermissionRestriction `json:"TriggerCreate"`
	TriggerDelete                     []UserPermissionRestriction `json:"TriggerDelete"`
	TriggerEdit                       []UserPermissionRestriction `json:"TriggerEdit"`
	TriggerView                       []UserPermissionRestriction `json:"TriggerView"`
	UserEdit                          []UserPermissionRestriction `json:"UserEdit"`
	UserInvite                        []UserPermissionRestriction `json:"UserInvite"`
	UserRoleEdit                      []UserPermissionRestriction `json:"UserRoleEdit"`
	UserRoleView                      []UserPermissionRestriction `json:"UserRoleView"`
	UserView                          []UserPermissionRestriction `json:"UserView"`
	VariableEdit                      []UserPermissionRestriction `json:"VariableEdit"`
	VariableEditUnscoped              []UserPermissionRestriction `json:"VariableEditUnscoped"`
	VariableView                      []UserPermissionRestriction `json:"VariableView"`
	VariableViewUnscoped              []UserPermissionRestriction `json:"VariableViewUnscoped"`
	WorkerEdit                        []UserPermissionRestriction `json:"WorkerEdit"`
	WorkerView                        []UserPermissionRestriction `json:"WorkerView"`
}
