package integration

const (
	serviceAccountService                 = "AccountService"
	serviceActionTemplateService          = "ActionTemplateService"
	serviceAPIKeyService                  = "APIKeyService"
	serviceArtifactService                = "ArtifactService"
	serviceAuthenticationService          = "AuthenticationService"
	serviceAzureDevOpService              = "AzureDevOpService"
	serviceBuildInformationService        = "BuildInformationService"
	serviceCertificateService             = "CertificateService"
	serviceChannelService                 = "ChannelService"
	serviceCommunityActionTemplateService = "CommunityActionTemplateService"
	serviceConfigurationService           = "ConfigurationService"
	serviceDeploymentService              = "DeploymentService"
	serviceDeploymentProcessService       = "DeploymentProcessService"
	serviceEnvironmentService             = "EnvironmentService"
	serviceFeedService                    = "FeedService"
	serviceInterruptionService            = "InterruptionService"
	serviceLibraryVariableSetService      = "LibraryVariableSetService"
	serviceLifecycleService               = "LifecycleService"
	serviceMachinePolicyService           = "MachinePolicyService"
	serviceMachineService                 = "MachineService"
	serviceProjectGroupService            = "ProjectGroupService"
	serviceProjectService                 = "ProjectService"
	serviceProjectTriggerService          = "ProjectTriggerService"
	serviceRootService                    = "RootService"
	serviceSpaceService                   = "SpaceService"
	serviceTagSetService                  = "TagSetService"
	serviceTenantService                  = "TenantService"
	serviceUserService                    = "UserService"
	serviceVariableService                = "VariableService"
)
