package constants

const (
	OperationAdd                      string = "Add"
	OperationAPIAdd                   string = "ApiAdd"
	OperationApiAddWithResponseStatus string = "ApiAddWithResponseStatus"
	OperationAPIDelete                string = "ApiDelete"
	OperationAPIGet                   string = "ApiGet"
	OperationAPIPost                  string = "ApiPost"
	OperationAPIUpdate                string = "ApiUpdate"
	OperationDelete                   string = "Delete"
	OperationDeleteByID               string = "DeleteByID"
	OperationGet                      string = "Get"
	OperationGetAddPath               string = "GetAddPath"
	OperationGetAPIKeyByID            string = "GetAPIKeyByID"
	OperationGetAPIKeys               string = "GetAPIKeys"
	OperationGetAuthentication        string = "GetAuthentication"
	OperationGetAuthenticationByUser  string = "GetAuthenticationByUser"
	OperationGetByID                  string = "GetByID"
	OperationGetByIDPath              string = "GetByIDPath"
	OperationGetByIDs                 string = "GetByIDs"
	OperationGetByName                string = "GetByName"
	OperationGetByNamePath            string = "GetByNamePath"
	OperationGetByPartialName         string = "GetByPartialName"
	OperationGetByPartialNamePath     string = "GetByPartialNamePath"
	OperationGetByProjectID           string = "GetByProjectID"
	OperationGetByUserID              string = "GetByUserID"
	OperationGetChannels              string = "GetChannels"
	OperationGetDeployments           string = "GetDeployments"
	OperationGetProject               string = "GetProject"
	OperationGetProjects              string = "GetProjects"
	OperationGetReleases              string = "GetReleases"
	OperationGetSummary               string = "GetSummary"
	OperationInstall                  string = "Install"
	OperationReplace                  string = "Replace"
	OperationSearchPackages           string = "SearchPackages"
	OperationUpdate                   string = "Update"
	OperationUpdatePath               string = "UpdatePath"
)
